using System;
using System.Collections.Generic;
using System.Linq;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using CBlunt.ANTLR.AutoGeneratedParser;
using System.Reflection;
using System.IO;

namespace CBlunt.ANTLR
{
    class CBluntCodeGenerator : CBluntBaseVisitor<int>
    {
        string path;
        public override int VisitStart([NotNull] CBluntParser.StartContext context)
        {
#if DEBUG
            Console.WriteLine("Beginning code generation");
            Console.WriteLine("VisitStart");
#endif
            using (StreamWriter stream = File.CreateText(this.path))
            {
                //Start by translating imports.
                stream.WriteLine("using System;");

                //Create the namespace for the translated code.
                stream.WriteLine("namespace CBCode {");

                //The class which houses the CBlunt Code.
                stream.WriteLine("class CBCode {");

                Visit(context);

                stream.WriteLine("}");

                stream.WriteLine("}");
            }
#if DEBUG
            Console.WriteLine("Finished code generation");
#endif
            return 0;
        }

        public CBluntCodeGenerator(string pathinsert) {
            string temppath = pathinsert;
            int count = 0;
            while (File.Exists(temppath)) {
                ++count;
                temppath = pathinsert + "_(" + count + ")";
            }
            this.path = temppath;
        }
    }
}