using System;
using System.Collections.Generic;
using System.Linq;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using CBlunt.ANTLR.AutoGeneratedParser;

//using OperandContext = CBlunt.ANTLR.AutoGeneratedParser.CBluntParser.OperandContext;
//using ExpressionContext = CBlunt.ANTLR.AutoGeneratedParser.CBluntParser.ExpressionContext;
using ExpressionContext = CBlunt.ANTLR.AutoGeneratedParser.CBluntParser.IdentifierContext;

namespace CBlunt.ANTLR
{
    internal class CBluntVisitor : CBluntBaseVisitor<int>
    {
        public override int VisitIdentifier([NotNull]ExpressionContext context)
        {
<<<<<<< HEAD
            Console.WriteLine("VisitIdentifier");
=======
            Console.WriteLine("Identifier");
>>>>>>> test-antlr
            return 0;
        }
    }
}
