using System;
using System.Collections.Generic;
using System.Linq;
using Antlr4.Runtime.Misc;
using CBlunt.ANTLR.AutoGeneratedParser;

namespace CBlunt.ANTLR
{
    class SymbolTableGenerator : CBluntBaseVisitor<int>
    {
        public override int VisitStart([NotNull] CBluntParser.StartContext context)
        {
#if DEBUG
            Console.WriteLine("Beginning symbol table generation");
            Console.WriteLine("VisitStart");
#endif
            // Create API methods first
            CreateAPIMethods();

            // Only visit functions as that is required of symboltable so far
            for (int i = 0; i < context.function().Count(); ++i)
                Visit(context.function(i));

#if DEBUG
            Console.WriteLine("Finished symbol table generation");
#endif
            return 0;
        }

        public override int VisitBlock([NotNull] CBluntParser.BlockContext context)
        {
            return base.VisitBlock(context);
        }

        public override int VisitFunction([NotNull] CBluntParser.FunctionContext context)
        {
#if DEBUG
            Console.WriteLine("VisitFunction");
#endif

            // The type of the method
            var methodType = context.functiontype().GetText();

            // The name of the method
            var methodName = context.ID(0).GetText();

            // The list of parameter types the method has
            var methodTypes = new List<string>();

            for (int i = 0; i < context.variabletype().Count(); ++i)
            {
                // Get the parameter type
                var methodParameter = context.variabletype(i).GetText();

                // Add it to the list of parameter types the method has
                methodTypes.Add(methodParameter);
            }

            // Create MethodProperties object
            var methodProperties = new MethodProperties
            {
                Type = methodType,
                ParameterTypes = methodTypes
            };

            // Add the method along with its properties to the symbol table
            CreateMethod(methodName, methodProperties);

            return base.VisitFunction(context);
        }

        void CreateAPIMethods()
        {
            // Helper variable for setting API functions methodproperties
            MethodProperties methodProperties;

            // WriteLine
            methodProperties = new MethodProperties
            {
                Type = "void",
                ParameterTypes = new List<string> { "text" }
            };

            CreateMethod("WriteLine", methodProperties);

            // ReadLine
            methodProperties = new MethodProperties
            {
                Type = "text",
                ParameterTypes = new List<string> { }
            };

            CreateMethod("ReadLine", methodProperties);
        }

        void CreateMethod(string methodName, MethodProperties methodProperties)
        {
            if (SymbolTable.MethodDictionary.ContainsKey(methodName))
            {
                Console.WriteLine("Symbol table generation error! Script contains declaration for API method with name: " + methodName);
                return;
            }

            // No need for check, program will error if method already exists
            SymbolTable.MethodDictionary.Add(methodName, methodProperties);
        }
    }

    /*
     * Store for a variable's properties
     */
    class VariableProperties
    {
        // The type of the variable (number, text, bool etc.)
        public string Type { get; set; }

        // Determine whether the variable has been initialized or not (aka null)
        // It is impossible to initialize a variable with null in CBlunt, therefore this only applies to ex:
        // number a;
        public bool Initialized { get; set; }

        // If not specified, the value of the variable is null
        public VariableProperties(string type, string value = null)
        {
            // Set the variable's type
            Type = type;

            if (value != null)
                Initialized = true;
        }
    }
}