//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CBlunt.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CBlunt.ANTLR.AutoGeneratedParser {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CBluntParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ICBluntVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] CBluntParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] CBluntParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] CBluntParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CBluntParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.idcall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdcall([NotNull] CBluntParser.IdcallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] CBluntParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.iterative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterative([NotNull] CBluntParser.IterativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.selective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelective([NotNull] CBluntParser.SelectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CBluntParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.idedit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdedit([NotNull] CBluntParser.IdeditContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CBluntParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CBluntParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogic([NotNull] CBluntParser.LogicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CBluntParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CBluntParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] CBluntParser.ParameterContext context);
}
} // namespace CBlunt.ANTLR.AutoGeneratedParser
